# Generated by Django 5.1.7 on 2025-03-25 05:26

import cuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaFormacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pf', models.CharField(max_length=50)),
                ('duracion', models.IntegerField(max_length=2)),
                ('niveles_formacion', models.IntegerField(choices=[(1, 'tecnico'), (2, 'tecnologo'), (3, 'operario')], default='1')),
                ('estado', models.IntegerField(choices=[(1, 'activo'), (2, 'inactivo')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default=cuid.cuid, editable=False, max_length=25, primary_key=True, serialize=False, unique=True)),
                ('numero_de_documento', models.IntegerField(unique=True)),
                ('tipo_de_documento', models.IntegerField(choices=[(1, 'CC'), (2, 'CE'), (3, 'NIT')])),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('direccion', models.TextField()),
                ('correo_electronico', models.EmailField(max_length=255, unique=True)),
                ('razon_social', models.CharField(default='no es empresa', max_length=255)),
                ('actividad_economica', models.CharField(default='desempleado', max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('numero_de_telefono', models.IntegerField(unique=True)),
                ('estado', models.IntegerField(choices=[(1, 'administrador'), (2, 'empresa'), (2, 'empresa')], default=1)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
