# Generated by Django 5.1.7 on 2025-03-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_programaformacion_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='estado',
            field=models.IntegerField(choices=[(1, 'administrador'), (2, 'empresa'), (3, 'sub_administrador')], default=1),
        ),
    ]
