# Generated by Django 5.1.7 on 2025-03-31 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='numero_de_telefono',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
