# Generated by Django 5.1.7 on 2025-03-31 09:29

import cuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_numero_de_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programaformacion',
            name='estado',
            field=models.IntegerField(choices=[(1, 'activo'), (2, 'inactivo'), (3, 'suspendido')], default=1),
        ),
        migrations.AlterField(
            model_name='programaformacion',
            name='id',
            field=models.CharField(default=cuid.cuid, editable=False, max_length=25, primary_key=True, serialize=False, unique=True),
        ),
    ]
