# Generated by Django 5.1.7 on 2025-04-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_programaformacion_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nombre',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
