# Generated by Django 5.1.7 on 2025-04-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.IntegerField(choices=[(1, 'administrador'), (2, 'empresa'), (3, 'sub_administrador')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='estado',
            field=models.IntegerField(choices=[(1, 'activo'), (2, 'inactivo')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='nombre',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='razon_social',
            field=models.CharField(default='no es empresa', max_length=255, unique=True),
        ),
    ]
